/dynamic_param: 1


/Crp450/Arm1_joint_p_gain_pose: 1.3
/Crp450/Arm1_joint_i_gain_pose: 0.07
/Crp450/Arm1_joint_d_gain_pose: 0.2
/Crp450/Arm1_joint_max_output_pose: 10

/Crp450/Arm1_joint_p_gain_vel: 0.05
/Crp450/Arm1_joint_i_gain_vel: 0.00166
/Crp450/Arm1_joint_d_gain_vel: 0.02
/Crp450/Arm1_joint_max_output_vel: 10


/Crp450/Arm2_joint_p_gain_pose: 3.7
/Crp450/Arm2_joint_i_gain_pose: 0.3
/Crp450/Arm2_joint_d_gain_pose: 0.035
/Crp450/Arm2_joint_max_output_pose: 10

/Crp450/Arm2_joint_p_gain_vel: 0.0396
/Crp450/Arm2_joint_i_gain_vel: 0.021
/Crp450/Arm2_joint_d_gain_vel: 0.091
/Crp450/Arm2_joint_max_output_vel: 10